name: flex_reminder
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  http: ^1.2.2
  share_plus: ^10.0.2
  url_launcher: ^6.3.0
  flutter_spinkit: ^5.2.0
  universal_io: ^2.2.0
  http_interceptor: ^2.0.0
  flutter_secure_storage: ^9.2.4
  cached_network_image: ^3.3.1
  image_picker: ^1.1.2
  flutter_html: ^3.0.0-beta.2
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.4
  receive_sharing_intent: ^1.8.1
  permission_handler: ^11.3.1
  intl: ^0.19.0
  awesome_notifications: ^0.10.1
  table_calendar: ^3.1.2
  shared_preferences: ^2.5.2
  fl_chart: ^0.68.0
  flutter_inappwebview: ^6.1.5
  provider: ^6.0.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1  # لتوليد الأيقونات تلقائيًا

dependency_overrides:
  intl: ^0.20.0  # للتوافق مع awesome_notifications

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/logo.png  # مسار الأيقونة الجديدة
  fonts:
    - family: arial
      fonts:
        - asset: assets/fonts/ARIAL.ttf
          weight: 400

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"  # مسار الأيقونة الأصلية
  min_sdk_android: 21  # الحد الأدنى لإصدار Android (اختياري)
